import "styles/globals.css";
import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { TRPCReactProvider } from "trpc/react";
import { Toaster } from "react-hot-toast";
import Providers from "./_components/Providers";
import LayoutClient from "./_components/LayoutClient";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="bg-black text-white w-[120vw] md:w-screen overflow-x-hidden">
        <Providers>
          <Toaster position="top-right" />
          <TRPCReactProvider>
            <LayoutClient>{children}</LayoutClient>
          </TRPCReactProvider>
        </Providers>
      </body>
    </html>
  );
}
